"""
NeoGap — Domain data models.

All dataclasses are intentionally plain (no ORM, no DB dependencies) so they
can be passed freely between services and serialised to JSON for logging.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Optional


# ---------------------------------------------------------------------------
# Enumerations
# ---------------------------------------------------------------------------

class GapDirection(str, Enum):
    UP = "GAP_UP"
    DOWN = "GAP_DOWN"
    NONE = "NO_GAP"


class SignalDirection(str, Enum):
    BUY = "BUY"       # Trade in gap direction (continuation) or counter (reversal)
    SELL = "SELL"
    NONE = "NONE"


class SignalBasis(str, Enum):
    CONTINUATION = "CONTINUATION"   # Historical gaps tend to continue
    REVERSAL = "REVERSAL"           # Historical gaps tend to fill/reverse
    INSUFFICIENT_DATA = "INSUFFICIENT_DATA"


class OrderSide(str, Enum):
    BUY = "B"
    SELL = "S"


class OrderType(str, Enum):
    MARKET = "MKT"
    LIMIT = "L"
    SL_MARKET = "SL-M"
    SL_LIMIT = "SL"


class PositionStatus(str, Enum):
    OPEN = "OPEN"
    PARTIAL = "PARTIAL"        # Partial exit taken at first target
    CLOSED = "CLOSED"
    STOPPED_OUT = "STOPPED_OUT"


class ExitReason(str, Enum):
    TARGET_1 = "TARGET_1"
    TARGET_2 = "TARGET_2"
    TRAILING_STOP = "TRAILING_STOP"
    STOP_LOSS = "STOP_LOSS"
    END_OF_DAY = "END_OF_DAY"
    MANUAL = "MANUAL"


# ---------------------------------------------------------------------------
# Gap analysis models
# ---------------------------------------------------------------------------

@dataclass
class DayOHLC:
    """One day's OHLC bar for a single symbol."""
    symbol: str
    date: datetime
    open: float
    high: float
    low: float
    close: float
    volume: int


@dataclass
class HistoricalGap:
    """A single historical gap event for trend analysis."""
    date: datetime
    gap_direction: GapDirection
    gap_pct: float          # Positive for gap-up, negative for gap-down
    prev_close: float
    open_price: float
    day_close: float
    # Did price continue in the gap direction (True) or fill/reverse (False)?
    is_continuation: bool
    continuation_pct: float  # How much it continued or reversed (absolute %)


@dataclass
class GapTrend:
    """
    Summary of historical gap behaviour for one symbol.
    Produced by GapTrendService and consumed by GapStrategy.
    """
    symbol: str
    direction: GapDirection         # Direction of gaps analysed (UP or DOWN)
    total_gaps: int
    continuation_count: int
    reversal_count: int

    @property
    def continuation_rate(self) -> float:
        if self.total_gaps == 0:
            return 0.0
        return self.continuation_count / self.total_gaps

    @property
    def reversal_rate(self) -> float:
        if self.total_gaps == 0:
            return 0.0
        return self.reversal_count / self.total_gaps

    avg_gap_pct: float = 0.0
    avg_continuation_pct: float = 0.0
    avg_reversal_pct: float = 0.0
    # Trend score 0–100: higher = stronger directional tendency
    trend_score: float = 0.0


@dataclass
class GapEvent:
    """
    Today's detected gap for a symbol at market open.
    """
    symbol: str
    detected_at: datetime
    gap_direction: GapDirection
    gap_pct: float          # Absolute percentage
    prev_close: float
    open_price: float
    avg_volume_20d: int
    today_volume: int       # Volume in first few minutes

    @property
    def volume_ratio(self) -> float:
        if self.avg_volume_20d == 0:
            return 0.0
        return self.today_volume / self.avg_volume_20d


# ---------------------------------------------------------------------------
# Signal model
# ---------------------------------------------------------------------------

@dataclass
class GapSignal:
    """
    Trading signal generated by GapStrategy after all filters pass.
    """
    symbol: str
    generated_at: datetime
    gap_event: GapEvent
    gap_trend: GapTrend
    signal_direction: SignalDirection   # BUY or SELL
    signal_basis: SignalBasis           # CONTINUATION or REVERSAL
    confidence_score: float             # 0–100
    entry_price: float
    stop_loss: float
    target_1: float
    target_2: float


# ---------------------------------------------------------------------------
# Position and order models
# ---------------------------------------------------------------------------

@dataclass
class Position:
    symbol: str
    signal: GapSignal
    entry_price: float
    quantity: int
    order_side: OrderSide
    status: PositionStatus = PositionStatus.OPEN
    entry_order_id: str = ""
    sl_order_id: str = ""
    target_order_id: str = ""
    current_price: float = 0.0
    highest_price: float = 0.0      # for trailing stop on longs
    lowest_price: float = 0.0       # for trailing stop on shorts
    trailing_stop: float = 0.0
    partial_exit_done: bool = False
    realised_pnl: float = 0.0
    unrealised_pnl: float = 0.0
    opened_at: Optional[datetime] = None
    closed_at: Optional[datetime] = None
    exit_reason: Optional[ExitReason] = None

    def update_trailing_stop(self, current_price: float, trailing_pct: float) -> None:
        if self.order_side == OrderSide.BUY:
            if current_price > self.highest_price:
                self.highest_price = current_price
            new_stop = self.highest_price * (1 - trailing_pct)
            if new_stop > self.trailing_stop:
                self.trailing_stop = new_stop
        else:
            if current_price < self.lowest_price or self.lowest_price == 0:
                self.lowest_price = current_price
            new_stop = self.lowest_price * (1 + trailing_pct)
            if self.trailing_stop == 0 or new_stop < self.trailing_stop:
                self.trailing_stop = new_stop

    def compute_unrealised_pnl(self, current_price: float) -> float:
        multiplier = 1 if self.order_side == OrderSide.BUY else -1
        self.current_price = current_price
        self.unrealised_pnl = (current_price - self.entry_price) * self.quantity * multiplier
        return self.unrealised_pnl


@dataclass
class TradeResult:
    symbol: str
    order_side: OrderSide
    entry_price: float
    exit_price: float
    quantity: int
    entry_time: datetime
    exit_time: datetime
    pnl: float
    exit_reason: ExitReason
    gap_pct: float
    signal_basis: SignalBasis


# ---------------------------------------------------------------------------
# Live quote
# ---------------------------------------------------------------------------

@dataclass
class LiveQuote:
    symbol: str
    ltp: float
    bid: float = 0.0
    ask: float = 0.0
    volume: int = 0
    timestamp: Optional[datetime] = None


# ---------------------------------------------------------------------------
# Daily metrics
# ---------------------------------------------------------------------------

@dataclass
class StrategyMetrics:
    date: datetime
    total_signals: int = 0
    total_trades: int = 0
    winning_trades: int = 0
    losing_trades: int = 0
    cumulative_pnl: float = 0.0
    max_drawdown: float = 0.0
    daily_loss: float = 0.0
    peak_pnl: float = 0.0

    @property
    def win_rate(self) -> float:
        if self.total_trades == 0:
            return 0.0
        return self.winning_trades / self.total_trades
